---
version: '3'

services:
  fract:
    container_name: fract
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/fract:latest
    networks:
      - fract-db
    depends_on:
      - redis
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - fract
    command:
      - stream
      - --file=/wd/fract.yml
      - --target=rate
      - --redis-host=redis:6379
      - --redis-db=0
    restart: always
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - fract-db
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always

networks:
  fract-db:

volumes:
  redis-data:
