version: '3'

services:
  fract:
    container_name: fract
    build:
      context: .
    depends_on:
      - redis
    command: '--version'
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
