---
version: '3'

services:
  trader:
    container_name: fract-trader
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/fract:dev
    networks:
      - fract-db
    depends_on:
      - streamer
      - redis
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - fract
    command:
      - open
      - --file=/wd/fract.yml
    restart: always
  streamer:
    container_name: fract-streamer
    image: dceoy/fract:dev
    networks:
      - fract-db
    depends_on:
      - redis
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - fract
    command:
      - stream
      - --file=/wd/fract.yml
      - --target=rate
      - --quiet
    restart: always
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - fract-db
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always

networks:
  fract-db:
    external: false

volumes:
  redis-data:
