version: '3'

services:
  fract:
    container_name: fract
    build:
      context: .
    restart: always
    environment:
      FRACTUS_YML: /host/fractus.yml
    volumes:
      - ${HOME}:/host
    command:
      - open
      - USD_JPY
      - EUR_USD
      - EUR_JPY
      - GBP_JPY
      - GBP_USD
      - EUR_GBP
