version: '3'

services:

  fract:
    container_name: fract
    entrypoint:
      - /bin/bash
      - -lc
    build:
      context: .
    depends_on:
      - redis
    command: 'fract --version'

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
